### ISSUE TITLE
Prevent text diffing across node borders

### ISSUE THREAD

**Issue by tobyzerner** [Teamwork/visual-dom-diff#45]
Hi @gkubisa, thanks for this great library!

I'm running into a bit of a strange issue in certain diffing scenarios, where the text is diffed all as one, instead of being interrupted by block-level nodes. This is leading to paragraphs that have not changed being duplicated. Here's an example:

![image](https://github.com/Teamwork/visual-dom-diff/assets/128862/eda9da83-0fa9-481d-9f5b-d20b1a043bf4)

Ideally this diff wouldn't touch the unchanged paragraphs.

Interestingly it only happens if the deleted and added text reaches a certain length compared to the unchanged paragraphs:

![image](https://github.com/Teamwork/visual-dom-diff/assets/128862/ee1b51de-6176-4f30-b1e6-177a3a3a10e6)

Any ideas how this can be solved?

**Comment by gkubisa** [comment]
If I remember correctly, `visual-dom-diff` removes the common prefix and suffix from the compared strings, and the rest is handled by https://www.npmjs.com/package/diff-match-patch.

In the first example you provide, the common prefix is very short ("This is a paragraph of text. ") and there is no common suffix. As the result, most of the diffing is done by `diff-match-patch`.

`diff-match-patch` is a generic plain-text diff algorithm, so it treats paragraph markers as any other characters. The algorithm applies heuristic to find the best possible diff, which might differ from what a human would call the best possible diff.

I have no ideas about how the library could be improved to produce better results for the example you provided.

**Comment by tobyzerner** [comment]
No worries, thanks @gkubisa. So is [this](https://github.com/google/diff-match-patch/wiki/Plain-Text-vs.-Structured-Content) an accurate description of how `visual-dom-diff` uses `diff-match-patch`?

> Another method is to walk the HTML and replace every opening and closing tag with a Unicode character. Check the Unicode spec for a range that is not in use. During the process, create a hash table of Unicode characters to the original tags. The result is a block of text which can be patched without fear of inserting text inside a tag or breaking the syntax of a tag. One just has to be careful when reconverting the content back to HTML that no closing tags are lost.

That page also states that a solution is to use a tree-based diff, but presumably implementing something like that for marginal gains would be beyond the scope of this library.

**Comment by gkubisa** [comment]
Yes, that's exactly what `visual-dom-diff` does and tree-based diff is definitely out of scope of this library.

**Comment by tobyzerner** [comment]
No worries, will close this as won't fix!
